---

- name: Check deb file
  stat:
    path: "/tmp/chronograf_{{ chronograf_version }}_amd64.deb"
  register: stat

- name: Get deb file
  get_url:
    url: "{{ chronograf_deb_url }}"
    dest: "/tmp/chronograf_{{ chronograf_version }}_amd64.deb"
    sha256sum: "{{ chronograf_deb_sha256sum }}"
  when: stat.stat.exists == False

- name: Install chronograf
  apt:
    state: present
    deb: "/tmp/chronograf_{{ chronograf_version }}_amd64.deb"
