---

- name: Download and install chronograf apt public signing key
  apt_key:
    url:   "{{ chronograf_signing_key_url }}"
    state: present

- name: Add chronograf apt repository definition to apt sources list
  apt_repository: 
    repo:         "{{ chronograf_apt_repo }}"
    update_cache: yes
    state:        present

- name: Install chronograf
  apt: name=chronograf state=present

- name: Update chronograf config file
  template:
    src:   config.toml.j2
    dest:  /opt/chronograf/config.toml
    owner: "{{ chronograf_user }}"
    group: "{{ chronograf_group }}"
    mode:  0664
  notify: Restart chronograf

- name: Update chronograf startup script envrionment variables file
  template:
    src:   etc.default.chronograf.j2
    dest:  /etc/default/chronograf
    owner: root
    group: root
    mode:  0664
  notify: Restart chronograf

- name: Start chronograf
  service: name=chronograf enabled=yes state=started
